#!/usr/bin/env python3
# media-bundler v1.0.0
# Python 3.10+
"""
media-bundler — group media anchors and related sidecar files into dated folders.

The workflow is intentionally conservative:

    discover -> plan -> preflight -> commit

Dry run is the default. No filesystem changes are made unless --execute is given.

Examples:
    media-bundler ~/Music/Exports
    media-bundler ~/Music/Exports --execute
    media-bundler ~/Audio --anchor wav,flac,aiff
    media-bundler ~/Projects --anchor wav,flac,aiff --recursive
    media-bundler ~/Projects --match prefix
    media-bundler ~/Projects --date-source created
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from dataclasses import dataclass
from datetime import datetime
from enum import Enum
from pathlib import Path
from typing import Iterable, Sequence


VERSION = "1.0.0"

DEFAULT_ANCHORS = ("wav",)
GENERATED_DIR_RE = re.compile(r".+ \(\d{4}-\d{2}-\d{2}\)$")
PREFIX_BOUNDARIES = frozenset({" ", "-", "_", ".", "(", "[", "{"})
IGNORED_NAMES = frozenset({".ds_store", "thumbs.db", "desktop.ini"})


class MediaBundlerError(RuntimeError):
    """Expected operational failure that should be shown without a traceback."""


class DateSource(str, Enum):
    AUTO = "auto"
    CREATED = "created"
    MODIFIED = "modified"


class MatchMode(str, Enum):
    EXACT = "exact"
    PREFIX = "prefix"


@dataclass(frozen=True)
class DatedValue:
    timestamp: float
    label: str
    fallback: bool = False

    @property
    def iso_date(self) -> str:
        return datetime.fromtimestamp(self.timestamp).strftime("%Y-%m-%d")


@dataclass(frozen=True)
class AnchorGroup:
    """Files sharing the same case-insensitive stem in one directory."""

    directory: Path
    stem_key: str
    display_stem: str
    preferred_anchor: Path
    anchor_files: tuple[Path, ...]


@dataclass(frozen=True)
class BundlePlan:
    group: AnchorGroup
    date: DatedValue
    destination: Path
    files: tuple[Path, ...]

    @property
    def name(self) -> str:
        return self.group.display_stem


def normalize_extension(value: str) -> str:
    value = value.strip().lower()
    while value.startswith("."):
        value = value[1:]
    if not value:
        raise argparse.ArgumentTypeError("anchor extension cannot be empty")
    if "/" in value or "\\" in value:
        raise argparse.ArgumentTypeError(
            f"invalid anchor extension {value!r}: extensions cannot contain path separators"
        )
    return value


def parse_anchor_values(values: Sequence[str] | None) -> tuple[str, ...]:
    if not values:
        return DEFAULT_ANCHORS

    parsed: list[str] = []
    seen: set[str] = set()
    for raw in values:
        for piece in raw.split(","):
            ext = normalize_extension(piece)
            if ext not in seen:
                seen.add(ext)
                parsed.append(ext)

    if not parsed:
        raise argparse.ArgumentTypeError("at least one anchor extension is required")
    return tuple(parsed)


def extension_key(path: Path) -> str:
    return path.suffix[1:].casefold() if path.suffix else ""


def is_ignored_file(path: Path) -> bool:
    name = path.name.casefold()
    return (
        name in IGNORED_NAMES
        or path.name.startswith("._")  # macOS AppleDouble metadata
    )


def is_generated_bundle_dir(path: Path) -> bool:
    return bool(GENERATED_DIR_RE.fullmatch(path.name))


def safe_resolve(path: Path, *, strict: bool) -> Path:
    try:
        return path.expanduser().resolve(strict=strict)
    except OSError as exc:
        raise MediaBundlerError(f"could not resolve path {path}: {exc}") from exc


def iter_directory_files(directory: Path) -> Iterable[Path]:
    try:
        entries = sorted(directory.iterdir(), key=lambda p: os.fsencode(p.name))
    except OSError as exc:
        raise MediaBundlerError(f"could not read directory {directory}: {exc}") from exc

    for entry in entries:
        try:
            if entry.is_symlink():
                continue
            if entry.is_file() and not is_ignored_file(entry):
                yield entry
        except OSError as exc:
            raise MediaBundlerError(f"could not inspect {entry}: {exc}") from exc


def walk_directories(root: Path, recursive: bool) -> Iterable[Path]:
    if not recursive:
        if not is_generated_bundle_dir(root):
            yield root
        return

    for current, dirnames, _filenames in os.walk(root, topdown=True, followlinks=False):
        current_path = Path(current)

        # Do not descend into symlinked directories or directories previously
        # generated by media-bundler.
        kept: list[str] = []
        for dirname in dirnames:
            child = current_path / dirname
            try:
                if child.is_symlink() or is_generated_bundle_dir(child):
                    continue
            except OSError:
                continue
            kept.append(dirname)
        dirnames[:] = sorted(kept, key=os.fsencode)

        if not is_generated_bundle_dir(current_path):
            yield current_path


def select_preferred_anchor(
    files: Sequence[Path],
    anchor_rank: dict[str, int],
) -> Path:
    return min(
        files,
        key=lambda path: (
            anchor_rank[extension_key(path)],
            os.fsencode(path.name),
        ),
    )


def discover_anchor_groups_in_directory(
    directory: Path,
    anchors: tuple[str, ...],
) -> tuple[list[AnchorGroup], tuple[Path, ...]]:
    files = tuple(iter_directory_files(directory))
    anchor_rank = {ext.casefold(): index for index, ext in enumerate(anchors)}

    grouped: dict[str, list[Path]] = {}
    for path in files:
        ext = extension_key(path)
        if ext not in anchor_rank:
            continue
        grouped.setdefault(path.stem.casefold(), []).append(path)

    groups: list[AnchorGroup] = []
    for stem_key, anchor_files in grouped.items():
        preferred = select_preferred_anchor(anchor_files, anchor_rank)
        groups.append(
            AnchorGroup(
                directory=directory,
                stem_key=stem_key,
                display_stem=preferred.stem,
                preferred_anchor=preferred,
                anchor_files=tuple(
                    sorted(anchor_files, key=lambda p: os.fsencode(p.name))
                ),
            )
        )

    groups.sort(key=lambda group: os.fsencode(group.display_stem.casefold()))
    return groups, files


def has_prefix_boundary(file_stem: str, anchor_stem: str) -> bool:
    if len(file_stem) <= len(anchor_stem):
        return False
    if not file_stem.startswith(anchor_stem):
        return False
    return file_stem[len(anchor_stem)] in PREFIX_BOUNDARIES


def assign_files_to_groups(
    groups: Sequence[AnchorGroup],
    files: Sequence[Path],
    match_mode: MatchMode,
) -> dict[str, list[Path]]:
    assignments: dict[str, list[Path]] = {group.stem_key: [] for group in groups}
    if not groups:
        return assignments

    group_by_stem = {group.stem_key: group for group in groups}
    anchor_paths = {
        anchor.resolve(strict=False): group.stem_key
        for group in groups
        for anchor in group.anchor_files
    }

    # Anchors always belong to their own stem group, even in prefix mode.
    for path in files:
        resolved = path.resolve(strict=False)
        owner = anchor_paths.get(resolved)
        if owner is not None:
            assignments[owner].append(path)

    for path in files:
        resolved = path.resolve(strict=False)
        if resolved in anchor_paths:
            continue

        stem_key = path.stem.casefold()

        # Exact stem match always wins.
        exact_group = group_by_stem.get(stem_key)
        if exact_group is not None:
            assignments[exact_group.stem_key].append(path)
            continue

        if match_mode != MatchMode.PREFIX:
            continue

        candidates = [
            group
            for group in groups
            if has_prefix_boundary(stem_key, group.stem_key)
        ]
        if not candidates:
            continue

        # Longest matching anchor stem wins. This prevents "Song Extended.png"
        # from being claimed by "Song" when "Song Extended" is also an anchor.
        winner = max(
            candidates,
            key=lambda group: (
                len(group.stem_key),
                group.stem_key,
            ),
        )
        assignments[winner.stem_key].append(path)

    for stem_key in assignments:
        assignments[stem_key].sort(key=lambda p: os.fsencode(p.name))

    return assignments


def creation_time(path: Path) -> float | None:
    try:
        stat = path.stat()
    except OSError as exc:
        raise MediaBundlerError(f"could not stat {path}: {exc}") from exc

    birthtime = getattr(stat, "st_birthtime", None)
    if birthtime is not None:
        return float(birthtime)

    if os.name == "nt":
        return float(stat.st_ctime)

    return None


def date_for_anchor(path: Path, source: DateSource) -> DatedValue:
    try:
        stat = path.stat()
    except OSError as exc:
        raise MediaBundlerError(f"could not stat {path}: {exc}") from exc

    if source == DateSource.MODIFIED:
        return DatedValue(float(stat.st_mtime), "modification time")

    created = creation_time(path)
    if created is not None:
        if os.name == "nt":
            label = "filesystem creation time"
        else:
            label = "filesystem birth time"
        return DatedValue(created, label)

    if source == DateSource.CREATED:
        raise MediaBundlerError(
            f"filesystem creation/birth time is unavailable for {path}; "
            "use --date-source auto or modified"
        )

    return DatedValue(
        float(stat.st_mtime),
        "modification time",
        fallback=True,
    )


def make_destination(group: AnchorGroup, date: DatedValue) -> Path:
    return group.directory / f"{group.display_stem} ({date.iso_date})"


def build_plans_for_directory(
    directory: Path,
    anchors: tuple[str, ...],
    match_mode: MatchMode,
    date_source: DateSource,
) -> list[BundlePlan]:
    groups, files = discover_anchor_groups_in_directory(directory, anchors)
    assignments = assign_files_to_groups(groups, files, match_mode)

    plans: list[BundlePlan] = []
    for group in groups:
        bundle_files = tuple(assignments[group.stem_key])
        if not bundle_files:
            continue
        dated = date_for_anchor(group.preferred_anchor, date_source)
        plans.append(
            BundlePlan(
                group=group,
                date=dated,
                destination=make_destination(group, dated),
                files=bundle_files,
            )
        )
    return plans


def collect_directories_and_explicit_files(
    targets: Sequence[Path],
    recursive: bool,
) -> tuple[list[Path], list[Path]]:
    directories: dict[Path, Path] = {}
    explicit_files: dict[Path, Path] = {}

    for raw_target in targets:
        expanded_target = raw_target.expanduser()
        try:
            if expanded_target.is_symlink():
                raise MediaBundlerError(
                    f"symlink targets are not supported: {expanded_target}"
                )
        except OSError as exc:
            raise MediaBundlerError(
                f"could not inspect target {expanded_target}: {exc}"
            ) from exc

        target = safe_resolve(expanded_target, strict=True)

        if target.is_file():
            explicit_files[target] = target
            continue

        if not target.is_dir():
            raise MediaBundlerError(f"not a regular file or directory: {target}")

        for directory in walk_directories(target, recursive):
            resolved = safe_resolve(directory, strict=True)
            directories[resolved] = resolved

    return (
        sorted(directories.values(), key=lambda p: os.fsencode(str(p))),
        sorted(explicit_files.values(), key=lambda p: os.fsencode(str(p))),
    )


def plan_explicit_file(
    path: Path,
    anchors: tuple[str, ...],
    match_mode: MatchMode,
    date_source: DateSource,
) -> BundlePlan:
    if extension_key(path) not in {ext.casefold() for ext in anchors}:
        raise MediaBundlerError(
            f"explicit file is not one of the configured anchor types "
            f"({', '.join('.' + ext for ext in anchors)}): {path}"
        )

    groups, files = discover_anchor_groups_in_directory(path.parent, anchors)
    target_group = next(
        (group for group in groups if path in group.anchor_files),
        None,
    )
    if target_group is None:
        raise MediaBundlerError(f"could not build an anchor group for {path}")

    assignments = assign_files_to_groups(groups, files, match_mode)
    dated = date_for_anchor(target_group.preferred_anchor, date_source)
    return BundlePlan(
        group=target_group,
        date=dated,
        destination=make_destination(target_group, dated),
        files=tuple(assignments[target_group.stem_key]),
    )


def collect_plans(
    targets: Sequence[Path],
    anchors: tuple[str, ...],
    match_mode: MatchMode,
    date_source: DateSource,
    recursive: bool,
) -> list[BundlePlan]:
    directories, explicit_files = collect_directories_and_explicit_files(
        targets,
        recursive,
    )

    plans_by_anchor: dict[Path, BundlePlan] = {}

    for directory in directories:
        for plan in build_plans_for_directory(
            directory,
            anchors,
            match_mode,
            date_source,
        ):
            key = plan.group.preferred_anchor.resolve(strict=False)
            plans_by_anchor[key] = plan

    for path in explicit_files:
        plan = plan_explicit_file(
            path,
            anchors,
            match_mode,
            date_source,
        )
        key = plan.group.preferred_anchor.resolve(strict=False)
        plans_by_anchor[key] = plan

    plans = list(plans_by_anchor.values())
    plans.sort(
        key=lambda plan: (
            os.fsencode(str(plan.group.directory)),
            os.fsencode(plan.group.display_stem.casefold()),
        )
    )
    return plans


def path_key(path: Path) -> str:
    """Normalize a path for duplicate/collision comparisons."""
    return os.path.normcase(os.path.abspath(os.fspath(path)))


def preflight(plans: Sequence[BundlePlan]) -> None:
    destinations: dict[str, BundlePlan] = {}
    source_owners: dict[str, BundlePlan] = {}

    for plan in plans:
        destination_key = path_key(plan.destination)
        previous_destination = destinations.get(destination_key)
        if previous_destination is not None:
            raise MediaBundlerError(
                "two bundles map to the same destination: "
                f"{previous_destination.destination} and {plan.destination}"
            )
        destinations[destination_key] = plan

        if plan.destination.exists():
            raise MediaBundlerError(
                f"destination already exists; refusing to merge or overwrite: "
                f"{plan.destination}"
            )

        expected_parent = path_key(plan.group.directory)
        if path_key(plan.destination.parent) != expected_parent:
            raise MediaBundlerError(
                f"destination escaped its source directory: {plan.destination}"
            )

        for source in plan.files:
            source_key = path_key(source)
            previous_owner = source_owners.get(source_key)
            if previous_owner is not None:
                raise MediaBundlerError(
                    f"source file belongs to more than one bundle: {source}"
                )
            source_owners[source_key] = plan

            if source.is_symlink():
                raise MediaBundlerError(
                    f"symlink source is not supported: {source}"
                )
            if not source.exists():
                raise MediaBundlerError(
                    f"source disappeared before execution: {source}"
                )
            if not source.is_file():
                raise MediaBundlerError(
                    f"source is no longer a regular file: {source}"
                )
            if path_key(source.parent) != expected_parent:
                raise MediaBundlerError(
                    f"source is outside the bundle directory: {source}"
                )

            target = plan.destination / source.name
            if target.exists():
                raise MediaBundlerError(
                    f"target file already exists: {target}"
                )


def print_plan(
    plans: Sequence[BundlePlan],
    *,
    execute: bool,
    anchors: tuple[str, ...],
    match_mode: MatchMode,
    date_source: DateSource,
) -> None:
    mode = "EXECUTE" if execute else "DRY RUN"
    print(f"media-bundler v{VERSION}")
    print(f"Mode: {mode}")
    print("Anchors: " + ", ".join(f".{ext}" for ext in anchors))
    print(f"Matching: {match_mode.value}")
    print(f"Date source: {date_source.value}")
    print()

    if not plans:
        print("No matching anchor files found.")
        return

    fallback_seen = False
    file_count = 0

    for plan in plans:
        file_count += len(plan.files)
        print(plan.name)
        print(f"  anchor       {plan.group.preferred_anchor.name}")
        print(f"  date         {plan.date.iso_date} ({plan.date.label})")
        if plan.date.fallback:
            fallback_seen = True
            print(
                "  warning      filesystem creation time unavailable; "
                "using modification time"
            )
        print(f"  destination  {plan.destination.name}/")
        print(f"  files        {len(plan.files)}")
        for source in plan.files:
            print(f"    -> {source.name}")
        print()

    print(f"Planned bundles: {len(plans)}")
    print(f"Planned files:   {file_count}")
    if fallback_seen:
        print(
            "Note: one or more anchors used modification time because a "
            "filesystem creation/birth time was unavailable."
        )


def move_bundle(plan: BundlePlan) -> None:
    """
    Commit one bundle as a unit.

    A failure attempts to roll back every file already moved into the new
    directory. Previously completed bundles are not rolled back.
    """
    # Revalidate immediately before mutation.
    if plan.destination.exists():
        raise MediaBundlerError(
            f"destination appeared after preflight: {plan.destination}"
        )

    for source in plan.files:
        if source.is_symlink() or not source.is_file():
            raise MediaBundlerError(
                f"source changed after preflight: {source}"
            )

    moved: list[tuple[Path, Path]] = []

    try:
        plan.destination.mkdir()
        for source in plan.files:
            target = plan.destination / source.name
            if target.exists():
                raise MediaBundlerError(
                    f"target appeared during execution: {target}"
                )
            source.rename(target)
            moved.append((source, target))
    except Exception as exc:
        rollback_errors: list[str] = []

        for source, target in reversed(moved):
            try:
                if source.exists():
                    rollback_errors.append(
                        f"cannot restore {target.name}: original pathname is occupied"
                    )
                    continue
                target.rename(source)
            except OSError as rollback_exc:
                rollback_errors.append(
                    f"could not restore {target} -> {source}: {rollback_exc}"
                )

        try:
            if plan.destination.exists() and not any(plan.destination.iterdir()):
                plan.destination.rmdir()
        except OSError as cleanup_exc:
            rollback_errors.append(
                f"could not remove empty destination {plan.destination}: {cleanup_exc}"
            )

        if rollback_errors:
            details = "; ".join(rollback_errors)
            raise MediaBundlerError(
                f"bundle failed and rollback was incomplete for {plan.name}: "
                f"{exc}; rollback errors: {details}"
            ) from exc

        if isinstance(exc, MediaBundlerError):
            raise
        raise MediaBundlerError(
            f"bundle failed; changes to this bundle were rolled back: "
            f"{plan.name}: {exc}"
        ) from exc


def execute_plans(plans: Sequence[BundlePlan]) -> None:
    for index, plan in enumerate(plans, start=1):
        print(
            f"[{index}/{len(plans)}] {plan.group.display_stem} "
            f"-> {plan.destination.name}/"
        )
        move_bundle(plan)
        print(f"  moved {len(plan.files)} file(s)")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="media-bundler",
        description=(
            "Group media files and related sidecars into dated folders. "
            "Dry run is the default; pass --execute to make changes."
        ),
        epilog=(
            "Anchor order determines priority when multiple configured anchor "
            "types share a basename. Existing destinations are never merged "
            "or overwritten."
        ),
    )
    parser.add_argument(
        "targets",
        nargs="+",
        type=Path,
        help="file or directory to inspect",
    )
    parser.add_argument(
        "--anchor",
        action="append",
        metavar="EXT[,EXT...]",
        help=(
            "anchor extension(s), ordered by priority; repeat or use commas "
            "(default: wav)"
        ),
    )
    parser.add_argument(
        "--match",
        choices=tuple(mode.value for mode in MatchMode),
        default=MatchMode.EXACT.value,
        help=(
            "sidecar matching mode: exact basename only, or prefix with a "
            "separator boundary (default: exact)"
        ),
    )
    parser.add_argument(
        "--date-source",
        choices=tuple(source.value for source in DateSource),
        default=DateSource.AUTO.value,
        help=(
            "folder date source: auto uses filesystem creation/birth time "
            "when available and modification time otherwise (default: auto)"
        ),
    )
    parser.add_argument(
        "-r",
        "--recursive",
        action="store_true",
        help="recurse into subdirectories",
    )
    parser.add_argument(
        "--execute",
        action="store_true",
        help="commit the planned moves; default is dry run",
    )
    parser.add_argument(
        "--version",
        action="version",
        version=f"%(prog)s {VERSION}",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)

    try:
        anchors = parse_anchor_values(args.anchor)
    except argparse.ArgumentTypeError as exc:
        parser.error(str(exc))

    match_mode = MatchMode(args.match)
    date_source = DateSource(args.date_source)

    try:
        plans = collect_plans(
            targets=args.targets,
            anchors=anchors,
            match_mode=match_mode,
            date_source=date_source,
            recursive=args.recursive,
        )
        preflight(plans)
    except MediaBundlerError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    except OSError as exc:
        print(f"error: filesystem failure: {exc}", file=sys.stderr)
        return 1

    print_plan(
        plans,
        execute=args.execute,
        anchors=anchors,
        match_mode=match_mode,
        date_source=date_source,
    )

    if not plans:
        return 0

    if not args.execute:
        print()
        print("Dry run complete. No changes made.")
        print("Re-run with --execute to commit this plan.")
        return 0

    print()
    try:
        execute_plans(plans)
    except MediaBundlerError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    except OSError as exc:
        print(f"error: filesystem failure: {exc}", file=sys.stderr)
        return 1

    print()
    print(f"Done. Bundled {len(plans)} item(s) successfully.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
